--liquibase formatted sql

--changeset vitno1:1
create table passport
(
    id           bigint generated by default as identity
        constraint passport_pkey
            primary key,
    issue_branch varchar(255),
    issue_date   date,
    number       varchar(255),
    series       varchar(255)
);
--rollback drop table passport;

--changeset vitno1:2
create table employment
(
    id                      bigint generated by default as identity
        constraint employment_pkey
            primary key,
    employer                varchar(255),
    employerinn             varchar(255),
    employment_status       integer,
    position                integer,
    salary                  numeric(19, 2),
    work_experience_current integer,
    work_experience_total   integer
);
--rollback drop table employment;

--changeset vitno1:3
create table credit
(
    id                   bigint generated by default as identity
        constraint credit_pkey
            primary key,
    amount               numeric(19, 2),
    credit_status        integer,
    is_insurance_enabled boolean,
    is_salary_client     boolean,
    monthly_payment      numeric(19, 2),
    psk                  numeric(19, 2),
    rate                 numeric(19, 2),
    term                 integer
);
--rollback drop table credit;

--changeset vitno1:4
create table loan_offerdtoentity
(
    application_id       bigint generated by default as identity
        constraint loan_offerdtoentity_pkey
            primary key,
    is_insurance_enabled boolean,
    is_salary_client     boolean,
    monthly_payment      numeric(19, 2),
    rate                 numeric(19, 2),
    requested_amount     numeric(19, 2),
    term                 integer,
    total_amount         numeric(19, 2)
);
--rollback drop table loan_offerdtoentity;

--changeset vitno1:5
create table payment_schedule_elementdtoentity
(
    id               bigint generated by default as identity
        constraint payment_schedule_elementdtoentity_pkey
            primary key,
    date             date,
    debt_payment     numeric(19, 2),
    interest_payment numeric(19, 2),
    number           integer,
    remaining_debt   numeric(19, 2),
    total_payment    numeric(19, 2),
    credit_id        bigint
        constraint fk4cvsqjjhiuyj6bx71fshclfxv
            references credit
);
--rollback drop table payment_schedule_elementdtoentity;

--changeset vitno1:6
create table client
(
    id               bigint generated by default as identity
        constraint client_pkey
            primary key,
    account          varchar(255),
    birth_date       date,
    dependent_amount integer,
    email            varchar(255),
    first_name       varchar(255),
    gender           integer,
    last_name        varchar(255),
    marital_status   integer,
    middle_name      varchar(255),
    employment_id    bigint
        constraint fk2otva1xnql5d427cmbvh9tjh7
            references employment,
    passport_id      bigint
        constraint fk12h145omp6r5ujc1typmdxixt
            references passport
);
--rollback drop table client;

--changeset vitno1:7
create table application
(
    id                 bigint generated by default as identity
        constraint application_pkey
            primary key,
    application_status integer,
    creation_date      date,
    ses_code           varchar(255),
    sign_date          date,
    appliedoffer_id    bigint
        constraint fk1mbakk5htt64749imm2qfvm72
            references loan_offerdtoentity,
    client_id          bigint
        constraint fksf5y1x7pt40gk6tvecgimmw7p
            references client,
    credit_id          bigint
        constraint fktivv032krrnua6gl76ey13mjm
            references credit
);
--rollback drop table application;

--changeset vitno1:8
create table application_status_historydtoentity
(
    id             bigint generated by default as identity
        constraint application_status_historydtoentity_pkey
            primary key,
    change_type    integer,
    status         integer,
    time           date,
    application_id bigint
        constraint fk6ubuadhb8dro2qwgrlw0g1o8f
            references application
);
--rollback drop table application_status_historydtoentity;












